from sqlalchemy import Column, BigInteger, Integer, String
from geoalchemy2 import Geometry

from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class OSMPoint(Base):
    __tablename__ = 'planet_osm_point'

    osm_id           = Column(BigInteger, primary_key=True)
    access           = Column(String)
    housename        = Column('addr:housename',String)
    housenumber      = Column('addr:housenumber',String)
    admin_level      = Column(String)
    aerialway        = Column(String)
    aeroway          = Column(String)
    amenity          = Column(String)
    barrier          = Column(String)
    boundary         = Column(String)
    building         = Column(String)
    highway          = Column(String)
    historic         = Column(String)
    junction         = Column(String)
    landuse          = Column(String)
    layer            = Column(Integer)
    leisure          = Column(String) 
    lock             = Column(String) 
    man_made         = Column(String) 
    military         = Column(String) 
    name             = Column(String) 
    natural          = Column(String) 
    oneway           = Column(String) 
    place            = Column(String) 
    power            = Column(String) 
    railway          = Column(String) 
    ref              = Column(String) 
    religion         = Column(String) 
    shop             = Column(String) 
    tourism          = Column(String) 
    water            = Column(String) 
    waterway         = Column(String) 
    tags             = Column(String)
    way              = Column(Geometry('POINT'))

class OSMPolygon(Base):
    __tablename__ = 'planet_osm_polygon'

    osm_id             = Column(BigInteger, primary_key=True)
    access             = Column(String)
    housename     = Column('addr:housename',String)
    housenumber   = Column('addr:housenumber',String)
    interpolation = Column('addr:interpolation',String)
    admin_level        = Column(String)
    aerialway          = Column(String)
    aeroway            = Column(String)
    amenity            = Column(String)
    barrier            = Column(String)
    bicycle            = Column(String)
    bridge             = Column(String)
    boundary           = Column(String)
    building           = Column(String)
    construction       = Column(String)
    covered            = Column(String)
    foot               = Column(String)
    highway            = Column(String)
    historic           = Column(String)
    horse              = Column(String)
    junction           = Column(String)
    landuse            = Column(String)
    layer              = Column(Integer)
    leisure            = Column(String)
    lock               = Column(String)
    man_made           = Column(String)
    military           = Column(String)
    name               = Column(String)
    natural            = Column(String)
    oneway             = Column(String)
    place              = Column(String)
    power              = Column(String)
    railway            = Column(String)
    ref                = Column(String)
    religion           = Column(String)
    route              = Column(String)
    service            = Column(String)
    shop               = Column(String)
    surface            = Column(String)
    tourism            = Column(String)
    tracktype          = Column(String)
    tunnel             = Column(String)
    water              = Column(String)
    waterway           = Column(String)
    way_area           = Column(String)
    z_order            = Column(String)
    tags               = Column(String)
    way                = Column(Geometry('POLYGON'))
 
class OSMRoads(Base):
    __tablename__ = 'planet_osm_roads'

    osm_id             = Column(BigInteger, primary_key=True) 
    access             = Column(String) 
    housename     = Column('addr:housename',String) 
    housenumber   = Column('addr:housenumber',String) 
    interpolation = Column('addr:interpolation',String) 
    admin_level        = Column(String)
    aerialway          = Column(String)
    aeroway            = Column(String)
    amenity            = Column(String)
    barrier            = Column(String)
    bicycle            = Column(String)
    bridge             = Column(String)
    boundary           = Column(String)
    building           = Column(String)
    construction       = Column(String)
    covered            = Column(String)
    foot               = Column(String)
    highway            = Column(String)
    historic           = Column(String)
    horse              = Column(String)
    junction           = Column(String)
    landuse            = Column(String)
    layer              = Column(Integer)
    leisure            = Column(String)
    lock               = Column(String)
    man_made           = Column(String)
    military           = Column(String)
    name               = Column(String)
    natural            = Column(String)
    oneway             = Column(String)
    place              = Column(String)
    power              = Column(String)
    railway            = Column(String)
    ref                = Column(String)
    religion           = Column(String)
    route              = Column(String)
    service            = Column(String)
    shop               = Column(String)
    surface            = Column(String)
    tourism            = Column(String)
    tracktype          = Column(String)
    tunnel             = Column(String)
    water              = Column(String)
    waterway           = Column(String)
    way_area           = Column(String)
    z_order            = Column(String)
    tags               = Column(String)
    way                = Column(Geometry('LINESTRING'))
 
class OSMLines(Base):
    __tablename__ = 'planet_osm_lines'

    osm_id             = Column(BigInteger, primary_key=True)
    access             = Column(String)
    housename     = Column('addr:housename',String)
    housenumber   = Column('addr:housenumber',String)
    interpolation = Column('addr:interpolation',String)
    admin_level        = Column(String)
    aerialway          = Column(String) 
    aeroway            = Column(String) 
    amenity            = Column(String) 
    barrier            = Column(String) 
    bicycle            = Column(String) 
    bridge             = Column(String) 
    boundary           = Column(String) 
    building           = Column(String) 
    construction       = Column(String) 
    covered            = Column(String) 
    foot               = Column(String) 
    highway            = Column(String) 
    historic           = Column(String) 
    horse              = Column(String) 
    junction           = Column(String) 
    landuse            = Column(String) 
    layer              = Column(Integer)
    leisure            = Column(String) 
    lock               = Column(String) 
    man_made           = Column(String) 
    military           = Column(String) 
    name               = Column(String) 
    natural            = Column(String) 
    oneway             = Column(String) 
    place              = Column(String) 
    power              = Column(String) 
    railway            = Column(String) 
    ref                = Column(String) 
    religion           = Column(String) 
    route              = Column(String) 
    service            = Column(String) 
    shop               = Column(String) 
    surface            = Column(String) 
    tourism            = Column(String) 
    tracktype          = Column(String) 
    tunnel             = Column(String) 
    water              = Column(String) 
    waterway           = Column(String) 
    way_area           = Column(String) 
    z_order            = Column(String) 
    tags               = Column(String) 
    way                = Column(Geometry('LINESTRING'))
